# Site settings

title: "Startupcasts"  

email: your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  Official blog for the “Between | Screens” micropodcast. Knowledge bombs from prolific designers and developers

paginate: 7
paginate_path: "/page/:num"

permalink: pretty
relative_permalinks: true

#baseurl: 'http://betweenpipes.com'
baseurl: ''

url: "http://www.betweenpipes.com" # the base hostname & protocol for your site
#url: "http://localhost:4000/" # the base hostname & protocol for your site

twitter_username: BetweenScreens_

#github_username:  jekyll

# Build settings
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass
